# Makefile.in generated by automake 1.16.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2018 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.





am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/libmutil
pkgincludedir = $(includedir)/libmutil
pkglibdir = $(libdir)/libmutil
pkglibexecdir = $(libexecdir)/libmutil
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-pc-linux-gnu
host_triplet = x86_64-pc-linux-gnu
#am__append_1 = -Wl,$(res_obj)
#am__append_2 = $(res_obj)
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/libmutil.m4 \
	$(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(top_srcdir)/configure \
	$(am__configure_deps) $(am__DIST_COMMON)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = $(top_builddir)/include/compilation_config.h
CONFIG_CLEAN_FILES = libmutil.pc
CONFIG_CLEAN_VPATH_FILES =
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
am__installdirs = "$(DESTDIR)$(libdir)" "$(DESTDIR)$(pkgconfigdir)"
LTLIBRARIES = $(lib_LTLIBRARIES)
am__DEPENDENCIES_1 =
am__libmutil_la_SOURCES_DIST = source/CriticalSection.cxx \
	source/MemObject.cxx source/LibraryPosix.cxx \
	source/MessageRouter.cxx source/Exception.cxx \
	source/massert.cxx source/IString.cxx source/dbg.cxx \
	source/merror.cxx source/TextUI.cxx source/Timestamp.cxx \
	source/mtime.cxx source/mtimePosix.cxx source/mtimeWin32.cxx \
	source/stringutils.cxx source/vmd5.cxx \
	source/CommandString.cxx source/XMLParser.cxx \
	source/MPluginPosix.cxx source/CircularBuffer.cxx \
	source/SipUri.cxx source/CacheItem.cxx \
	source/FileSystemUtils.cxx source/FileSystem.cxx \
	source/CondVarWin32.cxx source/MutexWin32.cxx \
	source/SemaphoreWin32.cxx source/ThreadWin32.cxx \
	source/CondVarPosix.cxx source/MutexPosix.cxx \
	source/SemaphorePosix.cxx source/ThreadPosix.cxx
am__objects_1 = libmutil_la-mtimePosix.lo
#am__objects_1 = libmutil_la-mtimeWin32.lo
##am__objects_2 =  \
##	libmutil_la-CondVarWin32.lo \
##	libmutil_la-MutexWin32.lo \
##	libmutil_la-SemaphoreWin32.lo \
##	libmutil_la-ThreadWin32.lo
am__objects_2 = libmutil_la-CondVarPosix.lo \
	libmutil_la-MutexPosix.lo \
	libmutil_la-SemaphorePosix.lo \
	libmutil_la-ThreadPosix.lo
am__objects_3 = libmutil_la-CriticalSection.lo \
	libmutil_la-MemObject.lo libmutil_la-LibraryPosix.lo \
	libmutil_la-MessageRouter.lo libmutil_la-Exception.lo \
	libmutil_la-massert.lo libmutil_la-IString.lo \
	libmutil_la-dbg.lo libmutil_la-merror.lo libmutil_la-TextUI.lo \
	libmutil_la-Timestamp.lo libmutil_la-mtime.lo $(am__objects_1) \
	libmutil_la-stringutils.lo libmutil_la-vmd5.lo \
	libmutil_la-CommandString.lo libmutil_la-XMLParser.lo \
	libmutil_la-MPluginPosix.lo libmutil_la-CircularBuffer.lo \
	libmutil_la-SipUri.lo libmutil_la-CacheItem.lo \
	libmutil_la-FileSystemUtils.lo libmutil_la-FileSystem.lo \
	$(am__objects_2)
am_libmutil_la_OBJECTS = $(am__objects_3)
libmutil_la_OBJECTS = $(am_libmutil_la_OBJECTS)
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
libmutil_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(libmutil_la_CXXFLAGS) \
	$(CXXFLAGS) $(libmutil_la_LDFLAGS) $(LDFLAGS) -o $@
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I. -I$(top_builddir)/include
depcomp = $(SHELL) $(top_srcdir)/config/depcomp
am__maybe_remake_depfiles = depfiles
am__depfiles_remade = ./$(DEPDIR)/libmutil_la-CacheItem.Plo \
	./$(DEPDIR)/libmutil_la-CircularBuffer.Plo \
	./$(DEPDIR)/libmutil_la-CommandString.Plo \
	./$(DEPDIR)/libmutil_la-CondVarPosix.Plo \
	./$(DEPDIR)/libmutil_la-CondVarWin32.Plo \
	./$(DEPDIR)/libmutil_la-CriticalSection.Plo \
	./$(DEPDIR)/libmutil_la-Exception.Plo \
	./$(DEPDIR)/libmutil_la-FileSystem.Plo \
	./$(DEPDIR)/libmutil_la-FileSystemUtils.Plo \
	./$(DEPDIR)/libmutil_la-IString.Plo \
	./$(DEPDIR)/libmutil_la-LibraryPosix.Plo \
	./$(DEPDIR)/libmutil_la-MPluginPosix.Plo \
	./$(DEPDIR)/libmutil_la-MemObject.Plo \
	./$(DEPDIR)/libmutil_la-MessageRouter.Plo \
	./$(DEPDIR)/libmutil_la-MutexPosix.Plo \
	./$(DEPDIR)/libmutil_la-MutexWin32.Plo \
	./$(DEPDIR)/libmutil_la-SemaphorePosix.Plo \
	./$(DEPDIR)/libmutil_la-SemaphoreWin32.Plo \
	./$(DEPDIR)/libmutil_la-SipUri.Plo \
	./$(DEPDIR)/libmutil_la-TextUI.Plo \
	./$(DEPDIR)/libmutil_la-ThreadPosix.Plo \
	./$(DEPDIR)/libmutil_la-ThreadWin32.Plo \
	./$(DEPDIR)/libmutil_la-Timestamp.Plo \
	./$(DEPDIR)/libmutil_la-XMLParser.Plo \
	./$(DEPDIR)/libmutil_la-dbg.Plo \
	./$(DEPDIR)/libmutil_la-massert.Plo \
	./$(DEPDIR)/libmutil_la-merror.Plo \
	./$(DEPDIR)/libmutil_la-mtime.Plo \
	./$(DEPDIR)/libmutil_la-mtimePosix.Plo \
	./$(DEPDIR)/libmutil_la-mtimeWin32.Plo \
	./$(DEPDIR)/libmutil_la-stringutils.Plo \
	./$(DEPDIR)/libmutil_la-vmd5.Plo
am__mv = mv -f
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
LTCXXCOMPILE = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CXXFLAGS) $(CXXFLAGS)
AM_V_CXX = $(am__v_CXX_$(V))
am__v_CXX_ = $(am__v_CXX_$(AM_DEFAULT_VERBOSITY))
am__v_CXX_0 = @echo "  CXX     " $@;
am__v_CXX_1 = 
CXXLD = $(CXX)
CXXLINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(AM_CXXFLAGS) \
	$(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CXXLD = $(am__v_CXXLD_$(V))
am__v_CXXLD_ = $(am__v_CXXLD_$(AM_DEFAULT_VERBOSITY))
am__v_CXXLD_0 = @echo "  CXXLD   " $@;
am__v_CXXLD_1 = 
SOURCES = $(libmutil_la_SOURCES)
DIST_SOURCES = $(am__libmutil_la_SOURCES_DIST)
RECURSIVE_TARGETS = all-recursive check-recursive cscopelist-recursive \
	ctags-recursive dvi-recursive html-recursive info-recursive \
	install-data-recursive install-dvi-recursive \
	install-exec-recursive install-html-recursive \
	install-info-recursive install-pdf-recursive \
	install-ps-recursive install-recursive installcheck-recursive \
	installdirs-recursive pdf-recursive ps-recursive \
	tags-recursive uninstall-recursive
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
DATA = $(pkgconfig_DATA)
RECURSIVE_CLEAN_TARGETS = mostlyclean-recursive clean-recursive	\
  distclean-recursive maintainer-clean-recursive
am__recursive_targets = \
  $(RECURSIVE_TARGETS) \
  $(RECURSIVE_CLEAN_TARGETS) \
  $(am__extra_recursive_targets)
AM_RECURSIVE_TARGETS = $(am__recursive_targets:-recursive=) TAGS CTAGS \
	cscope distdir distdir-am dist dist-all distcheck
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) $(LISP)
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
am__DIST_COMMON = $(srcdir)/Makefile.in $(srcdir)/libmutil.pc.in \
	$(top_srcdir)/config/compile $(top_srcdir)/config/config.guess \
	$(top_srcdir)/config/config.sub $(top_srcdir)/config/depcomp \
	$(top_srcdir)/config/install-sh $(top_srcdir)/config/ltmain.sh \
	$(top_srcdir)/config/missing AUTHORS COPYING.LIB ChangeLog \
	INSTALL NEWS README config/compile config/config.guess \
	config/config.sub config/depcomp config/install-sh \
	config/ltmain.sh config/missing
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
am__relativize = \
  dir0=`pwd`; \
  sed_first='s,^\([^/]*\)/.*$$,\1,'; \
  sed_rest='s,^[^/]*/*,,'; \
  sed_last='s,^.*/\([^/]*\)$$,\1,'; \
  sed_butlast='s,/*[^/]*$$,,'; \
  while test -n "$$dir1"; do \
    first=`echo "$$dir1" | sed -e "$$sed_first"`; \
    if test "$$first" != "."; then \
      if test "$$first" = ".."; then \
        dir2=`echo "$$dir0" | sed -e "$$sed_last"`/"$$dir2"; \
        dir0=`echo "$$dir0" | sed -e "$$sed_butlast"`; \
      else \
        first2=`echo "$$dir2" | sed -e "$$sed_first"`; \
        if test "$$first2" = "$$first"; then \
          dir2=`echo "$$dir2" | sed -e "$$sed_rest"`; \
        else \
          dir2="../$$dir2"; \
        fi; \
        dir0="$$dir0"/"$$first"; \
      fi; \
    fi; \
    dir1=`echo "$$dir1" | sed -e "$$sed_rest"`; \
  done; \
  reldir="$$dir2"
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/robin/data/minisip/libmutil/config/missing aclocal-1.16
ACLOCAL_FLAGS = 
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
AR = ar
AS = as
AUTOCONF = ${SHELL} /home/robin/data/minisip/libmutil/config/missing autoconf
AUTOHEADER = ${SHELL} /home/robin/data/minisip/libmutil/config/missing autoheader
AUTOMAKE = ${SHELL} /home/robin/data/minisip/libmutil/config/missing automake-1.16
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = gcc -E
CPPFLAGS = 
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DLLTOOL = dlltool
DSYMUTIL = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
EXTERNAL_CFLAGS =  -DHAVE_STRUCT_TIMEZONE -DHAVE_GETTIMEOFDAY
FGREP = /bin/grep -F
GREP = /bin/grep
INCLTDL = -I$(top_srcdir)/libltdl
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LD = /usr/bin/ld -m elf_x86_64
LDFLAGS = 
LIBLTDL = $(top_build_prefix)libltdl/libltdlc.la
LIBOBJS = 
LIBS = -ldl -lpthread 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = 
LN_S = ln -s
LTDLDEPS = $(top_build_prefix)libltdl/libltdlc.la
LTDLINCL = -I$(top_srcdir)/libltdl
LTLIBOBJS = 
LT_CURRENT_MINUS_AGE = 0
LT_SYS_LIBRARY_PATH = 
LT_VERSION_INFO = 0:0:0
MAINT = #
MAKEINFO = ${SHELL} /home/robin/data/minisip/libmutil/config/missing makeinfo
MANIFEST_TOOL = :
MINISIP_CFLAGS = -I$(top_srcdir)/include 
MINISIP_LIBRARY_LDFLAGS = -Wl,--no-undefined -no-undefined -version-info 0:0:0
MINISIP_LIBS = 
MKDIR_P = /bin/mkdir -p
MUTIL_MAJOR_VERSION = 0
MUTIL_MICRO_VERSION = 0
MUTIL_MINOR_VERSION = 8
NM = /usr/bin/nm -B
NMEDIT = 
OBJDUMP = objdump
OBJEXT = o
OTOOL = 
OTOOL64 = 
PACKAGE = libmutil
PACKAGE_BUGREPORT = Erik Eliasson <eliasson@imit.kth.se>
PACKAGE_NAME = libmutil
PACKAGE_STRING = libmutil 0.8.0+rUnversioned directory
PACKAGE_TARNAME = libmutil
PACKAGE_URL = 
PACKAGE_VERSION = 0.8.0+rUnversioned directory
PATH_SEPARATOR = :
PKG_CONFIG = /usr/bin/pkg-config
PKG_CONFIG_LIBDIR = 
PKG_CONFIG_PATH = 
PTHREAD_CFLAGS = -D_REENTRANT
PTHREAD_LIBS = 
PTHREAD_PATH = 
RANLIB = ranlib
SED = /bin/sed
SET_MAKE = 
SHELL = /bin/bash
STRIP = strip
VERSION = 0.8.0+rUnversioned directory
WINDRES = 
abs_builddir = /home/robin/data/minisip/libmutil
abs_srcdir = /home/robin/data/minisip/libmutil
abs_top_builddir = /home/robin/data/minisip/libmutil
abs_top_srcdir = /home/robin/data/minisip/libmutil
ac_ct_AR = ar
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build = x86_64-pc-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = pc
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-pc-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = pc
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/robin/data/minisip/libmutil/config/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
runstatedir = ${localstatedir}/run
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
subdirs =  libltdl
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
pkgconfigdir = $(libdir)/pkgconfig
SUBDIRS = libltdl include win32 . examples m4 debian
DIST_SUBDIRS = $(SUBDIRS)
EXTRA_DIST = libmutil.spec
INCLUDES = $(LTDLINCL)
pkgconfig_DATA = libmutil.pc
AM_CPPFLAGS = -I$(top_srcdir)/include $(EXTERNAL_CFLAGS)
lib_LTLIBRARIES = libmutil.la
libmutil_la_CXXFLAGS = $(PTHREAD_CFLAGS)
libmutil_la_LDFLAGS = $(MINISIP_LIBRARY_LDFLAGS) $(am__append_1)
libmutil_la_LIBADD = $(PTHREAD_LIBS) $(LIBLTDL)
libmutil_la_DEPENDENCIES = $(LIBLTDL) $(am__append_2)
libmutil_la_SOURCES = $(mutil_src)
#res_obj = win32/libmutil-res.o
##thread_src = source/CondVarWin32.cxx \
##		source/MutexWin32.cxx \
##		source/SemaphoreWin32.cxx \
##		source/ThreadWin32.cxx

thread_src = source/CondVarPosix.cxx \
	 	source/MutexPosix.cxx \
		source/SemaphorePosix.cxx \
		source/ThreadPosix.cxx

mtime_src = source/mtimePosix.cxx
#mtime_src = source/mtimeWin32.cxx
mutil_src = \
		source/CriticalSection.cxx \
		source/MemObject.cxx \
		source/LibraryPosix.cxx \
		source/MessageRouter.cxx \
		source/Exception.cxx \
		source/massert.cxx \
		source/IString.cxx \
		source/dbg.cxx \
		source/merror.cxx \
		source/TextUI.cxx \
		source/Timestamp.cxx \
		source/mtime.cxx \
		$(mtime_src) \
		source/stringutils.cxx \
		source/vmd5.cxx \
		source/CommandString.cxx \
		source/XMLParser.cxx \
		source/MPluginPosix.cxx \
		source/CircularBuffer.cxx \
		source/SipUri.cxx \
		source/CacheItem.cxx \
		source/FileSystemUtils.cxx \
		source/FileSystem.cxx \
		$(thread_src)


# maintainer rules
ACLOCAL_AMFLAGS = -I m4 $(ACLOCAL_FLAGS)
MAINTAINERCLEANFILES = \
		$(srcdir)/configure \
		$(srcdir)/Makefile.in \
		$(srcdir)/config/depcomp \
		$(srcdir)/config/config.sub \
		$(srcdir)/config/config.guess \
		$(srcdir)/config/install-sh \
		$(srcdir)/config/ltmain.sh \
		$(srcdir)/config/missing \
		$(srcdir)/missing \
		$(srcdir)/ltmain.sh \
		$(srcdir)/depcomp \
		$(srcdir)/config.guess \
		$(srcdir)/config.sub \
		$(srcdir)/install-sh \
		$(srcdir)/aclocal.m4

all: all-recursive

.SUFFIXES:
.SUFFIXES: .cxx .lo .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in: # $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --gnu \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --gnu Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__maybe_remake_depfiles)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__maybe_remake_depfiles);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure: # $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4): # $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):
libmutil.pc: $(top_builddir)/config.status $(srcdir)/libmutil.pc.in
	cd $(top_builddir) && $(SHELL) ./config.status $@

install-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	list2=; for p in $$list; do \
	  if test -f $$p; then \
	    list2="$$list2 $$p"; \
	  else :; fi; \
	done; \
	test -z "$$list2" || { \
	  echo " $(MKDIR_P) '$(DESTDIR)$(libdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(libdir)" || exit 1; \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 '$(DESTDIR)$(libdir)'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 "$(DESTDIR)$(libdir)"; \
	}

uninstall-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	for p in $$list; do \
	  $(am__strip_dir) \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f '$(DESTDIR)$(libdir)/$$f'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f "$(DESTDIR)$(libdir)/$$f"; \
	done

clean-libLTLIBRARIES:
	-test -z "$(lib_LTLIBRARIES)" || rm -f $(lib_LTLIBRARIES)
	@list='$(lib_LTLIBRARIES)'; \
	locs=`for p in $$list; do echo $$p; done | \
	      sed 's|^[^/]*$$|.|; s|/[^/]*$$||; s|$$|/so_locations|' | \
	      sort -u`; \
	test -z "$$locs" || { \
	  echo rm -f $${locs}; \
	  rm -f $${locs}; \
	}

libmutil.la: $(libmutil_la_OBJECTS) $(libmutil_la_DEPENDENCIES) $(EXTRA_libmutil_la_DEPENDENCIES) 
	$(AM_V_CXXLD)$(libmutil_la_LINK) -rpath $(libdir) $(libmutil_la_OBJECTS) $(libmutil_la_LIBADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/libmutil_la-CacheItem.Plo # am--include-marker
include ./$(DEPDIR)/libmutil_la-CircularBuffer.Plo # am--include-marker
include ./$(DEPDIR)/libmutil_la-CommandString.Plo # am--include-marker
include ./$(DEPDIR)/libmutil_la-CondVarPosix.Plo # am--include-marker
include ./$(DEPDIR)/libmutil_la-CondVarWin32.Plo # am--include-marker
include ./$(DEPDIR)/libmutil_la-CriticalSection.Plo # am--include-marker
include ./$(DEPDIR)/libmutil_la-Exception.Plo # am--include-marker
include ./$(DEPDIR)/libmutil_la-FileSystem.Plo # am--include-marker
include ./$(DEPDIR)/libmutil_la-FileSystemUtils.Plo # am--include-marker
include ./$(DEPDIR)/libmutil_la-IString.Plo # am--include-marker
include ./$(DEPDIR)/libmutil_la-LibraryPosix.Plo # am--include-marker
include ./$(DEPDIR)/libmutil_la-MPluginPosix.Plo # am--include-marker
include ./$(DEPDIR)/libmutil_la-MemObject.Plo # am--include-marker
include ./$(DEPDIR)/libmutil_la-MessageRouter.Plo # am--include-marker
include ./$(DEPDIR)/libmutil_la-MutexPosix.Plo # am--include-marker
include ./$(DEPDIR)/libmutil_la-MutexWin32.Plo # am--include-marker
include ./$(DEPDIR)/libmutil_la-SemaphorePosix.Plo # am--include-marker
include ./$(DEPDIR)/libmutil_la-SemaphoreWin32.Plo # am--include-marker
include ./$(DEPDIR)/libmutil_la-SipUri.Plo # am--include-marker
include ./$(DEPDIR)/libmutil_la-TextUI.Plo # am--include-marker
include ./$(DEPDIR)/libmutil_la-ThreadPosix.Plo # am--include-marker
include ./$(DEPDIR)/libmutil_la-ThreadWin32.Plo # am--include-marker
include ./$(DEPDIR)/libmutil_la-Timestamp.Plo # am--include-marker
include ./$(DEPDIR)/libmutil_la-XMLParser.Plo # am--include-marker
include ./$(DEPDIR)/libmutil_la-dbg.Plo # am--include-marker
include ./$(DEPDIR)/libmutil_la-massert.Plo # am--include-marker
include ./$(DEPDIR)/libmutil_la-merror.Plo # am--include-marker
include ./$(DEPDIR)/libmutil_la-mtime.Plo # am--include-marker
include ./$(DEPDIR)/libmutil_la-mtimePosix.Plo # am--include-marker
include ./$(DEPDIR)/libmutil_la-mtimeWin32.Plo # am--include-marker
include ./$(DEPDIR)/libmutil_la-stringutils.Plo # am--include-marker
include ./$(DEPDIR)/libmutil_la-vmd5.Plo # am--include-marker

$(am__depfiles_remade):
	@$(MKDIR_P) $(@D)
	@echo '# dummy' >$@-t && $(am__mv) $@-t $@

am--depfiles: $(am__depfiles_remade)

.cxx.o:
	$(AM_V_CXX)$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ $<

.cxx.obj:
	$(AM_V_CXX)$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.cxx.lo:
	$(AM_V_CXX)$(LTCXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Plo
#	$(AM_V_CXX)source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LTCXXCOMPILE) -c -o $@ $<

libmutil_la-CriticalSection.lo: source/CriticalSection.cxx
	$(AM_V_CXX)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -MT libmutil_la-CriticalSection.lo -MD -MP -MF $(DEPDIR)/libmutil_la-CriticalSection.Tpo -c -o libmutil_la-CriticalSection.lo `test -f 'source/CriticalSection.cxx' || echo '$(srcdir)/'`source/CriticalSection.cxx
	$(AM_V_at)$(am__mv) $(DEPDIR)/libmutil_la-CriticalSection.Tpo $(DEPDIR)/libmutil_la-CriticalSection.Plo
#	$(AM_V_CXX)source='source/CriticalSection.cxx' object='libmutil_la-CriticalSection.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -c -o libmutil_la-CriticalSection.lo `test -f 'source/CriticalSection.cxx' || echo '$(srcdir)/'`source/CriticalSection.cxx

libmutil_la-MemObject.lo: source/MemObject.cxx
	$(AM_V_CXX)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -MT libmutil_la-MemObject.lo -MD -MP -MF $(DEPDIR)/libmutil_la-MemObject.Tpo -c -o libmutil_la-MemObject.lo `test -f 'source/MemObject.cxx' || echo '$(srcdir)/'`source/MemObject.cxx
	$(AM_V_at)$(am__mv) $(DEPDIR)/libmutil_la-MemObject.Tpo $(DEPDIR)/libmutil_la-MemObject.Plo
#	$(AM_V_CXX)source='source/MemObject.cxx' object='libmutil_la-MemObject.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -c -o libmutil_la-MemObject.lo `test -f 'source/MemObject.cxx' || echo '$(srcdir)/'`source/MemObject.cxx

libmutil_la-LibraryPosix.lo: source/LibraryPosix.cxx
	$(AM_V_CXX)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -MT libmutil_la-LibraryPosix.lo -MD -MP -MF $(DEPDIR)/libmutil_la-LibraryPosix.Tpo -c -o libmutil_la-LibraryPosix.lo `test -f 'source/LibraryPosix.cxx' || echo '$(srcdir)/'`source/LibraryPosix.cxx
	$(AM_V_at)$(am__mv) $(DEPDIR)/libmutil_la-LibraryPosix.Tpo $(DEPDIR)/libmutil_la-LibraryPosix.Plo
#	$(AM_V_CXX)source='source/LibraryPosix.cxx' object='libmutil_la-LibraryPosix.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -c -o libmutil_la-LibraryPosix.lo `test -f 'source/LibraryPosix.cxx' || echo '$(srcdir)/'`source/LibraryPosix.cxx

libmutil_la-MessageRouter.lo: source/MessageRouter.cxx
	$(AM_V_CXX)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -MT libmutil_la-MessageRouter.lo -MD -MP -MF $(DEPDIR)/libmutil_la-MessageRouter.Tpo -c -o libmutil_la-MessageRouter.lo `test -f 'source/MessageRouter.cxx' || echo '$(srcdir)/'`source/MessageRouter.cxx
	$(AM_V_at)$(am__mv) $(DEPDIR)/libmutil_la-MessageRouter.Tpo $(DEPDIR)/libmutil_la-MessageRouter.Plo
#	$(AM_V_CXX)source='source/MessageRouter.cxx' object='libmutil_la-MessageRouter.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -c -o libmutil_la-MessageRouter.lo `test -f 'source/MessageRouter.cxx' || echo '$(srcdir)/'`source/MessageRouter.cxx

libmutil_la-Exception.lo: source/Exception.cxx
	$(AM_V_CXX)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -MT libmutil_la-Exception.lo -MD -MP -MF $(DEPDIR)/libmutil_la-Exception.Tpo -c -o libmutil_la-Exception.lo `test -f 'source/Exception.cxx' || echo '$(srcdir)/'`source/Exception.cxx
	$(AM_V_at)$(am__mv) $(DEPDIR)/libmutil_la-Exception.Tpo $(DEPDIR)/libmutil_la-Exception.Plo
#	$(AM_V_CXX)source='source/Exception.cxx' object='libmutil_la-Exception.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -c -o libmutil_la-Exception.lo `test -f 'source/Exception.cxx' || echo '$(srcdir)/'`source/Exception.cxx

libmutil_la-massert.lo: source/massert.cxx
	$(AM_V_CXX)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -MT libmutil_la-massert.lo -MD -MP -MF $(DEPDIR)/libmutil_la-massert.Tpo -c -o libmutil_la-massert.lo `test -f 'source/massert.cxx' || echo '$(srcdir)/'`source/massert.cxx
	$(AM_V_at)$(am__mv) $(DEPDIR)/libmutil_la-massert.Tpo $(DEPDIR)/libmutil_la-massert.Plo
#	$(AM_V_CXX)source='source/massert.cxx' object='libmutil_la-massert.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -c -o libmutil_la-massert.lo `test -f 'source/massert.cxx' || echo '$(srcdir)/'`source/massert.cxx

libmutil_la-IString.lo: source/IString.cxx
	$(AM_V_CXX)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -MT libmutil_la-IString.lo -MD -MP -MF $(DEPDIR)/libmutil_la-IString.Tpo -c -o libmutil_la-IString.lo `test -f 'source/IString.cxx' || echo '$(srcdir)/'`source/IString.cxx
	$(AM_V_at)$(am__mv) $(DEPDIR)/libmutil_la-IString.Tpo $(DEPDIR)/libmutil_la-IString.Plo
#	$(AM_V_CXX)source='source/IString.cxx' object='libmutil_la-IString.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -c -o libmutil_la-IString.lo `test -f 'source/IString.cxx' || echo '$(srcdir)/'`source/IString.cxx

libmutil_la-dbg.lo: source/dbg.cxx
	$(AM_V_CXX)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -MT libmutil_la-dbg.lo -MD -MP -MF $(DEPDIR)/libmutil_la-dbg.Tpo -c -o libmutil_la-dbg.lo `test -f 'source/dbg.cxx' || echo '$(srcdir)/'`source/dbg.cxx
	$(AM_V_at)$(am__mv) $(DEPDIR)/libmutil_la-dbg.Tpo $(DEPDIR)/libmutil_la-dbg.Plo
#	$(AM_V_CXX)source='source/dbg.cxx' object='libmutil_la-dbg.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -c -o libmutil_la-dbg.lo `test -f 'source/dbg.cxx' || echo '$(srcdir)/'`source/dbg.cxx

libmutil_la-merror.lo: source/merror.cxx
	$(AM_V_CXX)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -MT libmutil_la-merror.lo -MD -MP -MF $(DEPDIR)/libmutil_la-merror.Tpo -c -o libmutil_la-merror.lo `test -f 'source/merror.cxx' || echo '$(srcdir)/'`source/merror.cxx
	$(AM_V_at)$(am__mv) $(DEPDIR)/libmutil_la-merror.Tpo $(DEPDIR)/libmutil_la-merror.Plo
#	$(AM_V_CXX)source='source/merror.cxx' object='libmutil_la-merror.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -c -o libmutil_la-merror.lo `test -f 'source/merror.cxx' || echo '$(srcdir)/'`source/merror.cxx

libmutil_la-TextUI.lo: source/TextUI.cxx
	$(AM_V_CXX)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -MT libmutil_la-TextUI.lo -MD -MP -MF $(DEPDIR)/libmutil_la-TextUI.Tpo -c -o libmutil_la-TextUI.lo `test -f 'source/TextUI.cxx' || echo '$(srcdir)/'`source/TextUI.cxx
	$(AM_V_at)$(am__mv) $(DEPDIR)/libmutil_la-TextUI.Tpo $(DEPDIR)/libmutil_la-TextUI.Plo
#	$(AM_V_CXX)source='source/TextUI.cxx' object='libmutil_la-TextUI.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -c -o libmutil_la-TextUI.lo `test -f 'source/TextUI.cxx' || echo '$(srcdir)/'`source/TextUI.cxx

libmutil_la-Timestamp.lo: source/Timestamp.cxx
	$(AM_V_CXX)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -MT libmutil_la-Timestamp.lo -MD -MP -MF $(DEPDIR)/libmutil_la-Timestamp.Tpo -c -o libmutil_la-Timestamp.lo `test -f 'source/Timestamp.cxx' || echo '$(srcdir)/'`source/Timestamp.cxx
	$(AM_V_at)$(am__mv) $(DEPDIR)/libmutil_la-Timestamp.Tpo $(DEPDIR)/libmutil_la-Timestamp.Plo
#	$(AM_V_CXX)source='source/Timestamp.cxx' object='libmutil_la-Timestamp.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -c -o libmutil_la-Timestamp.lo `test -f 'source/Timestamp.cxx' || echo '$(srcdir)/'`source/Timestamp.cxx

libmutil_la-mtime.lo: source/mtime.cxx
	$(AM_V_CXX)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -MT libmutil_la-mtime.lo -MD -MP -MF $(DEPDIR)/libmutil_la-mtime.Tpo -c -o libmutil_la-mtime.lo `test -f 'source/mtime.cxx' || echo '$(srcdir)/'`source/mtime.cxx
	$(AM_V_at)$(am__mv) $(DEPDIR)/libmutil_la-mtime.Tpo $(DEPDIR)/libmutil_la-mtime.Plo
#	$(AM_V_CXX)source='source/mtime.cxx' object='libmutil_la-mtime.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -c -o libmutil_la-mtime.lo `test -f 'source/mtime.cxx' || echo '$(srcdir)/'`source/mtime.cxx

libmutil_la-mtimePosix.lo: source/mtimePosix.cxx
	$(AM_V_CXX)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -MT libmutil_la-mtimePosix.lo -MD -MP -MF $(DEPDIR)/libmutil_la-mtimePosix.Tpo -c -o libmutil_la-mtimePosix.lo `test -f 'source/mtimePosix.cxx' || echo '$(srcdir)/'`source/mtimePosix.cxx
	$(AM_V_at)$(am__mv) $(DEPDIR)/libmutil_la-mtimePosix.Tpo $(DEPDIR)/libmutil_la-mtimePosix.Plo
#	$(AM_V_CXX)source='source/mtimePosix.cxx' object='libmutil_la-mtimePosix.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -c -o libmutil_la-mtimePosix.lo `test -f 'source/mtimePosix.cxx' || echo '$(srcdir)/'`source/mtimePosix.cxx

libmutil_la-mtimeWin32.lo: source/mtimeWin32.cxx
	$(AM_V_CXX)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -MT libmutil_la-mtimeWin32.lo -MD -MP -MF $(DEPDIR)/libmutil_la-mtimeWin32.Tpo -c -o libmutil_la-mtimeWin32.lo `test -f 'source/mtimeWin32.cxx' || echo '$(srcdir)/'`source/mtimeWin32.cxx
	$(AM_V_at)$(am__mv) $(DEPDIR)/libmutil_la-mtimeWin32.Tpo $(DEPDIR)/libmutil_la-mtimeWin32.Plo
#	$(AM_V_CXX)source='source/mtimeWin32.cxx' object='libmutil_la-mtimeWin32.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -c -o libmutil_la-mtimeWin32.lo `test -f 'source/mtimeWin32.cxx' || echo '$(srcdir)/'`source/mtimeWin32.cxx

libmutil_la-stringutils.lo: source/stringutils.cxx
	$(AM_V_CXX)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -MT libmutil_la-stringutils.lo -MD -MP -MF $(DEPDIR)/libmutil_la-stringutils.Tpo -c -o libmutil_la-stringutils.lo `test -f 'source/stringutils.cxx' || echo '$(srcdir)/'`source/stringutils.cxx
	$(AM_V_at)$(am__mv) $(DEPDIR)/libmutil_la-stringutils.Tpo $(DEPDIR)/libmutil_la-stringutils.Plo
#	$(AM_V_CXX)source='source/stringutils.cxx' object='libmutil_la-stringutils.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -c -o libmutil_la-stringutils.lo `test -f 'source/stringutils.cxx' || echo '$(srcdir)/'`source/stringutils.cxx

libmutil_la-vmd5.lo: source/vmd5.cxx
	$(AM_V_CXX)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -MT libmutil_la-vmd5.lo -MD -MP -MF $(DEPDIR)/libmutil_la-vmd5.Tpo -c -o libmutil_la-vmd5.lo `test -f 'source/vmd5.cxx' || echo '$(srcdir)/'`source/vmd5.cxx
	$(AM_V_at)$(am__mv) $(DEPDIR)/libmutil_la-vmd5.Tpo $(DEPDIR)/libmutil_la-vmd5.Plo
#	$(AM_V_CXX)source='source/vmd5.cxx' object='libmutil_la-vmd5.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -c -o libmutil_la-vmd5.lo `test -f 'source/vmd5.cxx' || echo '$(srcdir)/'`source/vmd5.cxx

libmutil_la-CommandString.lo: source/CommandString.cxx
	$(AM_V_CXX)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -MT libmutil_la-CommandString.lo -MD -MP -MF $(DEPDIR)/libmutil_la-CommandString.Tpo -c -o libmutil_la-CommandString.lo `test -f 'source/CommandString.cxx' || echo '$(srcdir)/'`source/CommandString.cxx
	$(AM_V_at)$(am__mv) $(DEPDIR)/libmutil_la-CommandString.Tpo $(DEPDIR)/libmutil_la-CommandString.Plo
#	$(AM_V_CXX)source='source/CommandString.cxx' object='libmutil_la-CommandString.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -c -o libmutil_la-CommandString.lo `test -f 'source/CommandString.cxx' || echo '$(srcdir)/'`source/CommandString.cxx

libmutil_la-XMLParser.lo: source/XMLParser.cxx
	$(AM_V_CXX)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -MT libmutil_la-XMLParser.lo -MD -MP -MF $(DEPDIR)/libmutil_la-XMLParser.Tpo -c -o libmutil_la-XMLParser.lo `test -f 'source/XMLParser.cxx' || echo '$(srcdir)/'`source/XMLParser.cxx
	$(AM_V_at)$(am__mv) $(DEPDIR)/libmutil_la-XMLParser.Tpo $(DEPDIR)/libmutil_la-XMLParser.Plo
#	$(AM_V_CXX)source='source/XMLParser.cxx' object='libmutil_la-XMLParser.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -c -o libmutil_la-XMLParser.lo `test -f 'source/XMLParser.cxx' || echo '$(srcdir)/'`source/XMLParser.cxx

libmutil_la-MPluginPosix.lo: source/MPluginPosix.cxx
	$(AM_V_CXX)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -MT libmutil_la-MPluginPosix.lo -MD -MP -MF $(DEPDIR)/libmutil_la-MPluginPosix.Tpo -c -o libmutil_la-MPluginPosix.lo `test -f 'source/MPluginPosix.cxx' || echo '$(srcdir)/'`source/MPluginPosix.cxx
	$(AM_V_at)$(am__mv) $(DEPDIR)/libmutil_la-MPluginPosix.Tpo $(DEPDIR)/libmutil_la-MPluginPosix.Plo
#	$(AM_V_CXX)source='source/MPluginPosix.cxx' object='libmutil_la-MPluginPosix.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -c -o libmutil_la-MPluginPosix.lo `test -f 'source/MPluginPosix.cxx' || echo '$(srcdir)/'`source/MPluginPosix.cxx

libmutil_la-CircularBuffer.lo: source/CircularBuffer.cxx
	$(AM_V_CXX)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -MT libmutil_la-CircularBuffer.lo -MD -MP -MF $(DEPDIR)/libmutil_la-CircularBuffer.Tpo -c -o libmutil_la-CircularBuffer.lo `test -f 'source/CircularBuffer.cxx' || echo '$(srcdir)/'`source/CircularBuffer.cxx
	$(AM_V_at)$(am__mv) $(DEPDIR)/libmutil_la-CircularBuffer.Tpo $(DEPDIR)/libmutil_la-CircularBuffer.Plo
#	$(AM_V_CXX)source='source/CircularBuffer.cxx' object='libmutil_la-CircularBuffer.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -c -o libmutil_la-CircularBuffer.lo `test -f 'source/CircularBuffer.cxx' || echo '$(srcdir)/'`source/CircularBuffer.cxx

libmutil_la-SipUri.lo: source/SipUri.cxx
	$(AM_V_CXX)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -MT libmutil_la-SipUri.lo -MD -MP -MF $(DEPDIR)/libmutil_la-SipUri.Tpo -c -o libmutil_la-SipUri.lo `test -f 'source/SipUri.cxx' || echo '$(srcdir)/'`source/SipUri.cxx
	$(AM_V_at)$(am__mv) $(DEPDIR)/libmutil_la-SipUri.Tpo $(DEPDIR)/libmutil_la-SipUri.Plo
#	$(AM_V_CXX)source='source/SipUri.cxx' object='libmutil_la-SipUri.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -c -o libmutil_la-SipUri.lo `test -f 'source/SipUri.cxx' || echo '$(srcdir)/'`source/SipUri.cxx

libmutil_la-CacheItem.lo: source/CacheItem.cxx
	$(AM_V_CXX)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -MT libmutil_la-CacheItem.lo -MD -MP -MF $(DEPDIR)/libmutil_la-CacheItem.Tpo -c -o libmutil_la-CacheItem.lo `test -f 'source/CacheItem.cxx' || echo '$(srcdir)/'`source/CacheItem.cxx
	$(AM_V_at)$(am__mv) $(DEPDIR)/libmutil_la-CacheItem.Tpo $(DEPDIR)/libmutil_la-CacheItem.Plo
#	$(AM_V_CXX)source='source/CacheItem.cxx' object='libmutil_la-CacheItem.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -c -o libmutil_la-CacheItem.lo `test -f 'source/CacheItem.cxx' || echo '$(srcdir)/'`source/CacheItem.cxx

libmutil_la-FileSystemUtils.lo: source/FileSystemUtils.cxx
	$(AM_V_CXX)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -MT libmutil_la-FileSystemUtils.lo -MD -MP -MF $(DEPDIR)/libmutil_la-FileSystemUtils.Tpo -c -o libmutil_la-FileSystemUtils.lo `test -f 'source/FileSystemUtils.cxx' || echo '$(srcdir)/'`source/FileSystemUtils.cxx
	$(AM_V_at)$(am__mv) $(DEPDIR)/libmutil_la-FileSystemUtils.Tpo $(DEPDIR)/libmutil_la-FileSystemUtils.Plo
#	$(AM_V_CXX)source='source/FileSystemUtils.cxx' object='libmutil_la-FileSystemUtils.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -c -o libmutil_la-FileSystemUtils.lo `test -f 'source/FileSystemUtils.cxx' || echo '$(srcdir)/'`source/FileSystemUtils.cxx

libmutil_la-FileSystem.lo: source/FileSystem.cxx
	$(AM_V_CXX)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -MT libmutil_la-FileSystem.lo -MD -MP -MF $(DEPDIR)/libmutil_la-FileSystem.Tpo -c -o libmutil_la-FileSystem.lo `test -f 'source/FileSystem.cxx' || echo '$(srcdir)/'`source/FileSystem.cxx
	$(AM_V_at)$(am__mv) $(DEPDIR)/libmutil_la-FileSystem.Tpo $(DEPDIR)/libmutil_la-FileSystem.Plo
#	$(AM_V_CXX)source='source/FileSystem.cxx' object='libmutil_la-FileSystem.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -c -o libmutil_la-FileSystem.lo `test -f 'source/FileSystem.cxx' || echo '$(srcdir)/'`source/FileSystem.cxx

libmutil_la-CondVarWin32.lo: source/CondVarWin32.cxx
	$(AM_V_CXX)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -MT libmutil_la-CondVarWin32.lo -MD -MP -MF $(DEPDIR)/libmutil_la-CondVarWin32.Tpo -c -o libmutil_la-CondVarWin32.lo `test -f 'source/CondVarWin32.cxx' || echo '$(srcdir)/'`source/CondVarWin32.cxx
	$(AM_V_at)$(am__mv) $(DEPDIR)/libmutil_la-CondVarWin32.Tpo $(DEPDIR)/libmutil_la-CondVarWin32.Plo
#	$(AM_V_CXX)source='source/CondVarWin32.cxx' object='libmutil_la-CondVarWin32.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -c -o libmutil_la-CondVarWin32.lo `test -f 'source/CondVarWin32.cxx' || echo '$(srcdir)/'`source/CondVarWin32.cxx

libmutil_la-MutexWin32.lo: source/MutexWin32.cxx
	$(AM_V_CXX)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -MT libmutil_la-MutexWin32.lo -MD -MP -MF $(DEPDIR)/libmutil_la-MutexWin32.Tpo -c -o libmutil_la-MutexWin32.lo `test -f 'source/MutexWin32.cxx' || echo '$(srcdir)/'`source/MutexWin32.cxx
	$(AM_V_at)$(am__mv) $(DEPDIR)/libmutil_la-MutexWin32.Tpo $(DEPDIR)/libmutil_la-MutexWin32.Plo
#	$(AM_V_CXX)source='source/MutexWin32.cxx' object='libmutil_la-MutexWin32.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -c -o libmutil_la-MutexWin32.lo `test -f 'source/MutexWin32.cxx' || echo '$(srcdir)/'`source/MutexWin32.cxx

libmutil_la-SemaphoreWin32.lo: source/SemaphoreWin32.cxx
	$(AM_V_CXX)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -MT libmutil_la-SemaphoreWin32.lo -MD -MP -MF $(DEPDIR)/libmutil_la-SemaphoreWin32.Tpo -c -o libmutil_la-SemaphoreWin32.lo `test -f 'source/SemaphoreWin32.cxx' || echo '$(srcdir)/'`source/SemaphoreWin32.cxx
	$(AM_V_at)$(am__mv) $(DEPDIR)/libmutil_la-SemaphoreWin32.Tpo $(DEPDIR)/libmutil_la-SemaphoreWin32.Plo
#	$(AM_V_CXX)source='source/SemaphoreWin32.cxx' object='libmutil_la-SemaphoreWin32.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -c -o libmutil_la-SemaphoreWin32.lo `test -f 'source/SemaphoreWin32.cxx' || echo '$(srcdir)/'`source/SemaphoreWin32.cxx

libmutil_la-ThreadWin32.lo: source/ThreadWin32.cxx
	$(AM_V_CXX)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -MT libmutil_la-ThreadWin32.lo -MD -MP -MF $(DEPDIR)/libmutil_la-ThreadWin32.Tpo -c -o libmutil_la-ThreadWin32.lo `test -f 'source/ThreadWin32.cxx' || echo '$(srcdir)/'`source/ThreadWin32.cxx
	$(AM_V_at)$(am__mv) $(DEPDIR)/libmutil_la-ThreadWin32.Tpo $(DEPDIR)/libmutil_la-ThreadWin32.Plo
#	$(AM_V_CXX)source='source/ThreadWin32.cxx' object='libmutil_la-ThreadWin32.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -c -o libmutil_la-ThreadWin32.lo `test -f 'source/ThreadWin32.cxx' || echo '$(srcdir)/'`source/ThreadWin32.cxx

libmutil_la-CondVarPosix.lo: source/CondVarPosix.cxx
	$(AM_V_CXX)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -MT libmutil_la-CondVarPosix.lo -MD -MP -MF $(DEPDIR)/libmutil_la-CondVarPosix.Tpo -c -o libmutil_la-CondVarPosix.lo `test -f 'source/CondVarPosix.cxx' || echo '$(srcdir)/'`source/CondVarPosix.cxx
	$(AM_V_at)$(am__mv) $(DEPDIR)/libmutil_la-CondVarPosix.Tpo $(DEPDIR)/libmutil_la-CondVarPosix.Plo
#	$(AM_V_CXX)source='source/CondVarPosix.cxx' object='libmutil_la-CondVarPosix.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -c -o libmutil_la-CondVarPosix.lo `test -f 'source/CondVarPosix.cxx' || echo '$(srcdir)/'`source/CondVarPosix.cxx

libmutil_la-MutexPosix.lo: source/MutexPosix.cxx
	$(AM_V_CXX)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -MT libmutil_la-MutexPosix.lo -MD -MP -MF $(DEPDIR)/libmutil_la-MutexPosix.Tpo -c -o libmutil_la-MutexPosix.lo `test -f 'source/MutexPosix.cxx' || echo '$(srcdir)/'`source/MutexPosix.cxx
	$(AM_V_at)$(am__mv) $(DEPDIR)/libmutil_la-MutexPosix.Tpo $(DEPDIR)/libmutil_la-MutexPosix.Plo
#	$(AM_V_CXX)source='source/MutexPosix.cxx' object='libmutil_la-MutexPosix.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -c -o libmutil_la-MutexPosix.lo `test -f 'source/MutexPosix.cxx' || echo '$(srcdir)/'`source/MutexPosix.cxx

libmutil_la-SemaphorePosix.lo: source/SemaphorePosix.cxx
	$(AM_V_CXX)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -MT libmutil_la-SemaphorePosix.lo -MD -MP -MF $(DEPDIR)/libmutil_la-SemaphorePosix.Tpo -c -o libmutil_la-SemaphorePosix.lo `test -f 'source/SemaphorePosix.cxx' || echo '$(srcdir)/'`source/SemaphorePosix.cxx
	$(AM_V_at)$(am__mv) $(DEPDIR)/libmutil_la-SemaphorePosix.Tpo $(DEPDIR)/libmutil_la-SemaphorePosix.Plo
#	$(AM_V_CXX)source='source/SemaphorePosix.cxx' object='libmutil_la-SemaphorePosix.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -c -o libmutil_la-SemaphorePosix.lo `test -f 'source/SemaphorePosix.cxx' || echo '$(srcdir)/'`source/SemaphorePosix.cxx

libmutil_la-ThreadPosix.lo: source/ThreadPosix.cxx
	$(AM_V_CXX)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -MT libmutil_la-ThreadPosix.lo -MD -MP -MF $(DEPDIR)/libmutil_la-ThreadPosix.Tpo -c -o libmutil_la-ThreadPosix.lo `test -f 'source/ThreadPosix.cxx' || echo '$(srcdir)/'`source/ThreadPosix.cxx
	$(AM_V_at)$(am__mv) $(DEPDIR)/libmutil_la-ThreadPosix.Tpo $(DEPDIR)/libmutil_la-ThreadPosix.Plo
#	$(AM_V_CXX)source='source/ThreadPosix.cxx' object='libmutil_la-ThreadPosix.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libmutil_la_CXXFLAGS) $(CXXFLAGS) -c -o libmutil_la-ThreadPosix.lo `test -f 'source/ThreadPosix.cxx' || echo '$(srcdir)/'`source/ThreadPosix.cxx

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool config.lt
install-pkgconfigDATA: $(pkgconfig_DATA)
	@$(NORMAL_INSTALL)
	@list='$(pkgconfig_DATA)'; test -n "$(pkgconfigdir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(pkgconfigdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(pkgconfigdir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(pkgconfigdir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(pkgconfigdir)" || exit $$?; \
	done

uninstall-pkgconfigDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(pkgconfig_DATA)'; test -n "$(pkgconfigdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(pkgconfigdir)'; $(am__uninstall_files_from_dir)

# This directory's subdirectories are mostly independent; you can cd
# into them and run 'make' without going through this Makefile.
# To change the values of 'make' variables: instead of editing Makefiles,
# (1) if the variable is set in 'config.status', edit 'config.status'
#     (which will cause the Makefiles to be regenerated when you run 'make');
# (2) otherwise, pass the desired values on the 'make' command line.
$(am__recursive_targets):
	@fail=; \
	if $(am__make_keepgoing); then \
	  failcom='fail=yes'; \
	else \
	  failcom='exit 1'; \
	fi; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	case "$@" in \
	  distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
	  *) list='$(SUBDIRS)' ;; \
	esac; \
	for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-recursive
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	if ($(ETAGS) --etags-include --version) >/dev/null 2>&1; then \
	  include_option=--etags-include; \
	  empty_fix=.; \
	else \
	  include_option=--include; \
	  empty_fix=; \
	fi; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test ! -f $$subdir/TAGS || \
	      set "$$@" "$$include_option=$$here/$$subdir/TAGS"; \
	  fi; \
	done; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-recursive

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-recursive

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) distdir-am

distdir-am: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	@list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    $(am__make_dryrun) \
	      || test -d "$(distdir)/$$subdir" \
	      || $(MKDIR_P) "$(distdir)/$$subdir" \
	      || exit 1; \
	    dir1=$$subdir; dir2="$(distdir)/$$subdir"; \
	    $(am__relativize); \
	    new_distdir=$$reldir; \
	    dir1=$$subdir; dir2="$(top_distdir)"; \
	    $(am__relativize); \
	    new_top_distdir=$$reldir; \
	    echo " (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) top_distdir="$$new_top_distdir" distdir="$$new_distdir" \\"; \
	    echo "     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)"; \
	    ($(am__cd) $$subdir && \
	      $(MAKE) $(AM_MAKEFLAGS) \
	        top_distdir="$$new_top_distdir" \
	        distdir="$$new_distdir" \
		am__remove_distdir=: \
		am__skip_length_check=: \
		am__skip_mode_fix=: \
	        distdir) \
	      || exit 1; \
	  fi; \
	done
	$(MAKE) $(AM_MAKEFLAGS) \
	  top_distdir="$(top_distdir)" distdir="$(distdir)" \
	  dist-hook
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_build/sub $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build/sub \
	  && ../../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=../.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-recursive
all-am: Makefile $(LTLIBRARIES) $(DATA)
installdirs: installdirs-recursive
installdirs-am:
	for dir in "$(DESTDIR)$(libdir)" "$(DESTDIR)$(pkgconfigdir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-recursive
install-exec: install-exec-recursive
install-data: install-data-recursive
uninstall: uninstall-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-recursive
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
	-test -z "$(MAINTAINERCLEANFILES)" || rm -f $(MAINTAINERCLEANFILES)
clean: clean-recursive

clean-am: clean-generic clean-libLTLIBRARIES clean-libtool \
	mostlyclean-am

distclean: distclean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
		-rm -f ./$(DEPDIR)/libmutil_la-CacheItem.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-CircularBuffer.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-CommandString.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-CondVarPosix.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-CondVarWin32.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-CriticalSection.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-Exception.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-FileSystem.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-FileSystemUtils.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-IString.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-LibraryPosix.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-MPluginPosix.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-MemObject.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-MessageRouter.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-MutexPosix.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-MutexWin32.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-SemaphorePosix.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-SemaphoreWin32.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-SipUri.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-TextUI.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-ThreadPosix.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-ThreadWin32.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-Timestamp.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-XMLParser.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-dbg.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-massert.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-merror.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-mtime.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-mtimePosix.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-mtimeWin32.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-stringutils.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-vmd5.Plo
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-libtool distclean-tags

dvi: dvi-recursive

dvi-am:

html: html-recursive

html-am:

info: info-recursive

info-am:

install-data-am: install-pkgconfigDATA

install-dvi: install-dvi-recursive

install-dvi-am:

install-exec-am: install-libLTLIBRARIES

install-html: install-html-recursive

install-html-am:

install-info: install-info-recursive

install-info-am:

install-man:

install-pdf: install-pdf-recursive

install-pdf-am:

install-ps: install-ps-recursive

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
		-rm -f ./$(DEPDIR)/libmutil_la-CacheItem.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-CircularBuffer.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-CommandString.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-CondVarPosix.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-CondVarWin32.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-CriticalSection.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-Exception.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-FileSystem.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-FileSystemUtils.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-IString.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-LibraryPosix.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-MPluginPosix.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-MemObject.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-MessageRouter.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-MutexPosix.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-MutexWin32.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-SemaphorePosix.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-SemaphoreWin32.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-SipUri.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-TextUI.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-ThreadPosix.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-ThreadWin32.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-Timestamp.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-XMLParser.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-dbg.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-massert.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-merror.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-mtime.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-mtimePosix.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-mtimeWin32.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-stringutils.Plo
	-rm -f ./$(DEPDIR)/libmutil_la-vmd5.Plo
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic \
	maintainer-clean-local

mostlyclean: mostlyclean-recursive

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-recursive

pdf-am:

ps: ps-recursive

ps-am:

uninstall-am: uninstall-libLTLIBRARIES uninstall-pkgconfigDATA

.MAKE: $(am__recursive_targets) install-am install-strip

.PHONY: $(am__recursive_targets) CTAGS GTAGS TAGS all all-am \
	am--depfiles am--refresh check check-am clean clean-cscope \
	clean-generic clean-libLTLIBRARIES clean-libtool cscope \
	cscopelist-am ctags ctags-am dist dist-all dist-bzip2 \
	dist-gzip dist-hook dist-lzip dist-shar dist-tarZ dist-xz \
	dist-zip distcheck distclean distclean-compile \
	distclean-generic distclean-libtool distclean-tags \
	distcleancheck distdir distuninstallcheck dvi dvi-am html \
	html-am info info-am install install-am install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-libLTLIBRARIES install-man install-pdf \
	install-pdf-am install-pkgconfigDATA install-ps install-ps-am \
	install-strip installcheck installcheck-am installdirs \
	installdirs-am maintainer-clean maintainer-clean-generic \
	maintainer-clean-local mostlyclean mostlyclean-compile \
	mostlyclean-generic mostlyclean-libtool pdf pdf-am ps ps-am \
	tags tags-am uninstall uninstall-am uninstall-libLTLIBRARIES \
	uninstall-pkgconfigDATA

.PRECIOUS: Makefile


maintainer-clean-local:
	rm -rf $(srcdir)/libltdl

dist-hook:
	cp -a version $(distdir)/.version

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
